#!/bin/bash

################################################################################
# WARNING: DO NOT EDIT THIS FILE MANUALLY!
#
# This file is automatically downloaded and managed by the egg installer.
# Any manual changes you make will be overwritten on the next update.
#
# To customize server settings, use the egg configuration variables in your
# Pelican or Pterodactyl panel instead.
################################################################################

DOWNLOADER="./hytale-downloader-linux-amd64"

# Function to extract downloaded server files
extract_server_files() {
    echo "Extrayendo archivos de servidor..."
    SERVER_ZIP="server.zip"

    if [ -f "$SERVER_ZIP" ]; then
        echo "Se encontró descarga: $SERVER_ZIP"

        # Extract to current directory
        unzip -o "$SERVER_ZIP"

        if [ $? -ne 0 ]; then
            echo "Error: Fallo al extraer $SERVER_ZIP"
            exit 1
        fi

        echo "Extracción completa."

        # Move contents from Server folder to current directory
        if [ -d "Server" ]; then
            echo "Moviendo archivos..."
            mv Server/* .
            rmdir Server
            echo "✓ Archivos de servidor movidos a la raíz exitosamente."
        fi

        # Clean up the zip file
        echo "Limpiando archivos..."
        rm "$SERVER_ZIP"
        echo "✓ Limpieza finalizada."
    else
        echo "Error: Archivo de servidor no encontrado $SERVER_ZIP"
        exit 1
    fi
}

# Check if the downloader exists
if [ ! -f "$DOWNLOADER" ]; then
    echo "Error: Descargador Hytale no encontrado!"
    echo "Solicita la reinstalación de tu servidor en nuestras plataformas de atención."
    exit 1
fi

# Check if the downloader is executable
if [ ! -x "$DOWNLOADER" ]; then
    echo "Estableciendo permisos ..."
    chmod +x "$DOWNLOADER"
fi

# Check if credentials file exists, if not run the updater
if [ ! -f ".hytale-downloader-credentials.json" ]; then
    echo "Credenciales no encontradas, actualizando archivos de servidor..."
    echo "Descargando Hytale..."
    $DOWNLOADER -check-update
    $DOWNLOADER -patchline $PATCHLINE -download-path server.zip
    extract_server_files
fi

# Run automatic update if enabled
if [ "${AUTOMATIC_UPDATE}" = "1" ]; then
    echo "Descargando Hytale..."
    $DOWNLOADER -check-update
    $DOWNLOADER -patchline $PATCHLINE -download-path server.zip
    extract_server_files
fi

# Check if server files were downloaded correctly
if [ ! -f "HytaleServer.jar" ]; then
    echo "Error: Servidor de Hytale no encontrado!"
    echo "Archivos de servidor no se han descargado correctamente, ponte en contacto con nosotros."
    exit 1
fi

# Obtain authentication tokens
echo "Obteniendo tokens de autenticación..."

# Step 1: Request device code
AUTH_RESPONSE=$(curl -s -X POST "https://oauth.accounts.hytale.com/oauth2/device/auth" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "client_id=hytale-server" \
  -d "scope=openid offline auth:server")

# Extract device_code and verification_uri_complete using jq
DEVICE_CODE=$(echo "$AUTH_RESPONSE" | jq -r '.device_code')
VERIFICATION_URI=$(echo "$AUTH_RESPONSE" | jq -r '.verification_uri_complete')
POLL_INTERVAL=$(echo "$AUTH_RESPONSE" | jq -r '.interval')

# Display authentication banner
echo ""
echo "╔═════════════════════════════════════════════════════════════════════════════╗"
echo "║                       SE REQUIERE AUTENTICACIÓN DE USUARIO                  ║"
echo "╠═════════════════════════════════════════════════════════════════════════════╣"
echo "║                                                                             ║"
echo "║  Por favor autentica tu servidor visitando el siguiente link:               ║"
echo "║                                                                             ║"
echo "║  $VERIFICATION_URI  ║"
echo "║                                                                             ║"
echo "║  1. Clickea el link de arriba o cópialo a tu navegador                      ║"
echo "║  2. Inicia sesión con tu cuenta Hytale                                      ║"
echo "║  3. Autoriza el servidor                                                    ║"
echo "║                                                                             ║"
echo "║  Esperando autenticación...                                                 ║"
echo "║                                                                             ║"
echo "╚═════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Step 2: Poll for access token
ACCESS_TOKEN=""
while [ -z "$ACCESS_TOKEN" ]; do
    sleep $POLL_INTERVAL

    TOKEN_RESPONSE=$(curl -s -X POST "https://oauth.accounts.hytale.com/oauth2/token" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      -d "client_id=hytale-server" \
      -d "grant_type=urn:ietf:params:oauth:grant-type:device_code" \
      -d "device_code=$DEVICE_CODE")

    # Check if we got an error
    ERROR=$(echo "$TOKEN_RESPONSE" | jq -r '.error // empty')

    if [ "$ERROR" = "authorization_pending" ]; then
        echo "Aún esperando autenticación..."
        continue
    elif [ -n "$ERROR" ]; then
        echo "Error de autenticación: $ERROR"
        exit 1
    else
        # Successfully authenticated
        ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
        echo ""
        echo "✓ Autenticación exitosa!"
        echo ""
    fi
done

# Fetch available game profiles
echo "Obteniendo perfiles de juego..."

PROFILES_RESPONSE=$(curl -s -X GET "https://account-data.hytale.com/my-account/get-profiles" \
  -H "Authorization: Bearer $ACCESS_TOKEN")

# Check if profiles list is empty
PROFILES_COUNT=$(echo "$PROFILES_RESPONSE" | jq '.profiles | length')

if [ "$PROFILES_COUNT" -eq 0 ]; then
    echo "Error: No se han encontrado perfiles. Debes comprar Hytale para tener tu servidor o ponte contáctate con nosotros."
    exit 1
fi

# Select profile based on GAME_PROFILE variable
if [ -n "$GAME_PROFILE" ]; then
    # User specified a profile username, find matching UUID
    echo "Buscando perfil: $GAME_PROFILE"
    PROFILE_UUID=$(echo "$PROFILES_RESPONSE" | jq -r ".profiles[] | select(.username == \"$GAME_PROFILE\") | .uuid")

    if [ -z "$PROFILE_UUID" ] || [ "$PROFILE_UUID" = "null" ]; then
        echo "Error: Perfil '$GAME_PROFILE' no encontrado."
        echo "Perfiles disponibles:"
        echo "$PROFILES_RESPONSE" | jq -r '.profiles[] | "  - \(.username)"'
        exit 1
    fi

    echo "✓ Usando perfil: $GAME_PROFILE (UUID: $PROFILE_UUID)"
else
    # Use first profile from the list
    PROFILE_UUID=$(echo "$PROFILES_RESPONSE" | jq -r '.profiles[0].uuid')
    PROFILE_USERNAME=$(echo "$PROFILES_RESPONSE" | jq -r '.profiles[0].username')

    echo "✓ Usando perfil por defecto: $PROFILE_USERNAME (UUID: $PROFILE_UUID)"
fi

echo ""

# Create game server session
echo "Creando sesión de servidor..."

SESSION_RESPONSE=$(curl -s -X POST "https://sessions.hytale.com/game-session/new" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"uuid\": \"${PROFILE_UUID}\"}")

# Validate JSON response
if ! echo "$SESSION_RESPONSE" | jq empty 2>/dev/null; then
    echo "Error: Error al crear la sesión de servidor"
    echo "Respuesta: $SESSION_RESPONSE"
    exit 1
fi

# Extract session and identity tokens
SESSION_TOKEN=$(echo "$SESSION_RESPONSE" | jq -r '.sessionToken')
IDENTITY_TOKEN=$(echo "$SESSION_RESPONSE" | jq -r '.identityToken')

if [ -z "$SESSION_TOKEN" ] || [ "$SESSION_TOKEN" = "null" ]; then
    echo "Error: Fallo al crear sesión de servidor"
    echo "Respuesta: $SESSION_RESPONSE"
    exit 1
fi

echo "✓ Sesión de servidor de Hytale creada exitosamente!"
echo ""

echo "Iniciando servidor Hytale..."

# Build the Java command
JAVA_CMD="java"

# Add AOT cache if enabled
if [ "${LEVERAGE_AHEAD_OF_TIME_CACHE}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} -XX:AOTCache=HytaleServer.aot"
fi

# Add max memory if set and greater than 0
if [ -n "${SERVER_MEMORY}" ] && [ "${SERVER_MEMORY}" -gt 0 ] 2>/dev/null; then
    JAVA_CMD="${JAVA_CMD} -Xms${SERVER_MEMORY}M -Xmx${SERVER_MEMORY}M"
fi

# Add JVM arguments if set
if [ -n "${JVM_ARGS}" ]; then
    JAVA_CMD="${JAVA_CMD} ${JVM_ARGS}"
fi

JAVA_CMD="${JAVA_CMD} -jar HytaleServer.jar"

# Add assets parameter if set and ends with .zip
if [ -n "${ASSET_PACK}" ] && [[ "${ASSET_PACK}" == *.zip ]]; then
    JAVA_CMD="${JAVA_CMD} --assets ${ASSET_PACK}"
fi

# Add accept-early-plugins flag if variable is set
if [ "${ACCEPT_EARLY_PLUGINS}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --accept-early-plugins"
fi

JAVA_CMD="${JAVA_CMD} --auth-mode ${AUTH_MODE}"

# Add allow-op flag if variable is set
if [ "${ALLOW_OP}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --allow-op"
fi

# Add disable-sentry flag if enabled
if [ "${DISABLE_SENTRY}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --disable-sentry"
fi

# Add backup parameters if enabled
if [ "${ENABLE_BACKUPS}" = "1" ]; then
    JAVA_CMD="${JAVA_CMD} --backup --backup-dir ${BACKUP_DIRECTORY} --backup-frequency ${BACKUP_FREQUENCY}"
fi

# Add session tokens and owner UUID
JAVA_CMD="${JAVA_CMD} --session-token ${SESSION_TOKEN}"
JAVA_CMD="${JAVA_CMD} --identity-token ${IDENTITY_TOKEN}"
JAVA_CMD="${JAVA_CMD} --owner-uuid ${PROFILE_UUID}"

# Add bind address
JAVA_CMD="${JAVA_CMD} --bind 0.0.0.0:${SERVER_PORT}"

# Execute the command
eval $JAVA_CMD
